### ISSUE TITLE
Please add Admin panel simple

### ISSUE THREAD

**Issue by Arabiain** [gothx2009/MyForum#8]
Hello my friend
Thank you very much for the excellent excellent script, its very beautiful idea simple and fast.
Please add the feature of adding sections and categories to the forum.
Thank you very much for sharing this wonderful script.

**Comment by Arabiain** [comment]
Home page needs Pagination
post page Pagination's  is excellent

**Comment by Arabiain** [comment]
Please add a feature to upload an image or file within the topic

**Comment by gothx2009** [comment]
Due to the lack of an actual authentication system, a full administration panel is not currently in the roadmap.  Our system relies on an administrator defined Personal Identification Number (PIN) that is hardcoded into the system.  This forum is designed to be as minimalistic as possible, though we may add it in further updates.

Categories/Sections are possible, but may not be added in the near future.

The pagination on the homepage is in works, just been a slow work due to personal time.

Image uploads may or may not be added, due to the risk of XSS on file includes.  We may revisit this in the future.

**Comment by gothx2009** [comment]
Pagination request is referenced in Issue #1 (This request will be addressed in the next update.)

**Comment by gothx2009** [comment]
Fixed in #9

**Comment by Arabiain** [comment]
Thank you very much my dear friend, great job, nice update and waiting for further updates.
What is Hooks function? An error occurred when running the script, so I stopped the script

**Comment by Arabiain** [comment]
There is a problem that I cannot use the delete feature, as it does not delete the post, what is the reason ?!

**Comment by Arabiain** [comment]
![مشكلة الحذف](https://user-images.githubusercontent.com/8568779/94376296-6500d000-0122-11eb-887f-7f9803727ad0.jpg)
 problem that I cannot use the delete
